# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'

target 'RNAccountKit' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for RNAccountKit
  pod 'AccountKit'
  pod 'yoga', path: '../node_modules/react-native/ReactCommon/yoga'
  pod 'React', path: '../node_modules/react-native'


end
